[2022-08-23 04:03:29,078: INFO: main]: 
***************************
[2022-08-23 04:03:29,079: INFO: main]: >>>>>>>>>>> stage   MAIN   started <<<<<<<<<<
[2022-08-23 04:03:29,848: ERROR: main]: Run (ID '0e5460610eb94931991ae9bc8beb04fe') failed
Traceback (most recent call last):
  File "src/main.py", line 30, in <module>
    main()
  File "src/main.py", line 22, in main
    mlflow.run(".", "get_data", use_conda = False)
  File "C:\Users\ASUS\anaconda3\envs\MLFLOW-CNN\lib\site-packages\mlflow\projects\__init__.py", line 346, in run
    _wait_for(submitted_run_obj)
  File "C:\Users\ASUS\anaconda3\envs\MLFLOW-CNN\lib\site-packages\mlflow\projects\__init__.py", line 363, in _wait_for
    raise ExecutionException("Run (ID '%s') failed" % run_id)
mlflow.exceptions.ExecutionException: Run (ID '0e5460610eb94931991ae9bc8beb04fe') failed
[2022-08-23 04:07:34,850: INFO: main]: 
***************************
[2022-08-23 04:07:34,851: INFO: main]: >>>>>>>>>>> stage   MAIN   started <<<<<<<<<<
[2022-08-23 04:07:35,621: ERROR: main]: Run (ID 'b44a1a7379f142bf8e5c6dd64ae14722') failed
Traceback (most recent call last):
  File "src/main.py", line 30, in <module>
    main()
  File "src/main.py", line 22, in main
    mlflow.run(".", "get_data", use_conda = False)
  File "C:\Users\ASUS\anaconda3\envs\MLFLOW-CNN\lib\site-packages\mlflow\projects\__init__.py", line 346, in run
    _wait_for(submitted_run_obj)
  File "C:\Users\ASUS\anaconda3\envs\MLFLOW-CNN\lib\site-packages\mlflow\projects\__init__.py", line 363, in _wait_for
    raise ExecutionException("Run (ID '%s') failed" % run_id)
mlflow.exceptions.ExecutionException: Run (ID 'b44a1a7379f142bf8e5c6dd64ae14722') failed
[2022-08-23 04:08:12,975: INFO: main]: 
***************************
[2022-08-23 04:08:12,975: INFO: main]: >>>>>>>>>>> stage   MAIN   started <<<<<<<<<<
[2022-08-23 04:08:13,699: ERROR: main]: Run (ID '7685dcb31f1e48bcb1fda177dba4cb72') failed
Traceback (most recent call last):
  File "src/main.py", line 30, in <module>
    main()
  File "src/main.py", line 22, in main
    mlflow.run(".", "get_data", use_conda = False)
  File "C:\Users\ASUS\anaconda3\envs\MLFLOW-CNN\lib\site-packages\mlflow\projects\__init__.py", line 346, in run
    _wait_for(submitted_run_obj)
  File "C:\Users\ASUS\anaconda3\envs\MLFLOW-CNN\lib\site-packages\mlflow\projects\__init__.py", line 363, in _wait_for
    raise ExecutionException("Run (ID '%s') failed" % run_id)
mlflow.exceptions.ExecutionException: Run (ID '7685dcb31f1e48bcb1fda177dba4cb72') failed
[2022-08-23 04:09:49,140: INFO: main]: 
***************************
[2022-08-23 04:09:49,140: INFO: main]: >>>>>>>>>>> stage   MAIN   started <<<<<<<<<<
[2022-08-23 04:09:49,909: INFO: stage__01__get__data]: 
***************************
[2022-08-23 04:09:49,909: INFO: stage__01__get__data]: >>>>>>>>>>> stage   DATA LOAD   started <<<<<<<<<<
[2022-08-23 04:09:49,912: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-08-23 04:09:49,912: INFO: common]: created directory at: data
[2022-08-23 04:09:49,912: INFO: data_mgmt]: function execution started
[2022-08-23 04:09:49,912: INFO: common]: created directory at: bad_data
[2022-08-23 04:10:06,901: INFO: stage__01__get__data]: >>>>>>>>> stage  DATA LOAD   completed <<<<<<<<<<<
[2022-08-23 04:10:13,008: INFO: stage__02__base__model__creation]: 
***************************
[2022-08-23 04:10:13,009: INFO: stage__02__base__model__creation]: >>>>>>>>>>> stage   INITIAL MODEL CREATION   started <<<<<<<<<<
[2022-08-23 04:10:13,010: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-08-23 04:10:13,011: INFO: stage__02__base__model__creation]: layers are about to be defined
[2022-08-23 04:10:13,029: INFO: stage__02__base__model__creation]: layers are defined
[2022-08-23 04:10:13,202: INFO: stage__02__base__model__creation]: log model summary: 
 Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 conv2d (Conv2D)             (None, 178, 178, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 89, 89, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 87, 87, 32)        9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 43, 43, 32)       0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 59168)             0         
                                                                 
 dense (Dense)               (None, 128)               7573632   
                                                                 
 dense_1 (Dense)             (None, 2)                 258       
                                                                 
=================================================================
Total params: 7,584,034
Trainable params: 7,584,034
Non-trainable params: 0
_________________________________________________________________

[2022-08-23 04:10:13,214: INFO: common]: created directory at: data\model
[2022-08-23 04:10:13,315: INFO: stage__02__base__model__creation]: model is saved at data\model\init_model.h5
[2022-08-23 04:10:13,315: INFO: stage__02__base__model__creation]: >>>>>>>>> stage  INITIAL MODEL CREATION   completed <<<<<<<<<<<
[2022-08-23 04:10:13,724: INFO: main]: >>>>>>>>> stage  MAIN   completed <<<<<<<<<<<
[2022-08-23 04:15:38,890: INFO: main]: 
***************************
[2022-08-23 04:15:38,890: INFO: main]: >>>>>>>>>>> stage   MAIN   started <<<<<<<<<<
[2022-08-23 04:15:39,824: ERROR: main]: Run (ID '370ea16d95024884a65036959df62a1e') failed
Traceback (most recent call last):
  File "src/main.py", line 30, in <module>
    main()
  File "src/main.py", line 22, in main
    mlflow.run(".", "get_data", use_conda = False)
  File "C:\Users\ASUS\anaconda3\envs\MLFLOW-CNN\lib\site-packages\mlflow\projects\__init__.py", line 346, in run
    _wait_for(submitted_run_obj)
  File "C:\Users\ASUS\anaconda3\envs\MLFLOW-CNN\lib\site-packages\mlflow\projects\__init__.py", line 363, in _wait_for
    raise ExecutionException("Run (ID '%s') failed" % run_id)
mlflow.exceptions.ExecutionException: Run (ID '370ea16d95024884a65036959df62a1e') failed
[2022-08-23 04:16:11,916: INFO: main]: 
***************************
[2022-08-23 04:16:11,916: INFO: main]: >>>>>>>>>>> stage   MAIN   started <<<<<<<<<<
[2022-08-23 04:16:12,747: ERROR: main]: Run (ID '14b164e55f9b4d3fb6a10f73b7bce94b') failed
Traceback (most recent call last):
  File "src/main.py", line 30, in <module>
    main()
  File "src/main.py", line 22, in main
    mlflow.run(".", "get_data", use_conda = False)
  File "C:\Users\ASUS\anaconda3\envs\MLFLOW-CNN\lib\site-packages\mlflow\projects\__init__.py", line 346, in run
    _wait_for(submitted_run_obj)
  File "C:\Users\ASUS\anaconda3\envs\MLFLOW-CNN\lib\site-packages\mlflow\projects\__init__.py", line 363, in _wait_for
    raise ExecutionException("Run (ID '%s') failed" % run_id)
mlflow.exceptions.ExecutionException: Run (ID '14b164e55f9b4d3fb6a10f73b7bce94b') failed
[2022-08-23 04:17:16,887: INFO: main]: 
***************************
[2022-08-23 04:17:16,887: INFO: main]: >>>>>>>>>>> stage   MAIN   started <<<<<<<<<<
[2022-08-23 04:17:17,672: INFO: stage__01__get__data]: 
***************************
[2022-08-23 04:17:17,672: INFO: stage__01__get__data]: >>>>>>>>>>> stage   DATA LOAD   started <<<<<<<<<<
[2022-08-23 04:17:17,674: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-08-23 04:17:17,674: INFO: common]: created directory at: data
[2022-08-23 04:17:17,674: INFO: data_mgmt]: function execution started
[2022-08-23 04:17:17,674: INFO: common]: created directory at: bad_data
[2022-08-23 04:17:22,042: INFO: stage__01__get__data]: >>>>>>>>> stage  DATA LOAD   completed <<<<<<<<<<<
[2022-08-23 04:17:25,130: INFO: stage__02__base__model__creation]: 
***************************
[2022-08-23 04:17:25,131: INFO: stage__02__base__model__creation]: >>>>>>>>>>> stage   INITIAL MODEL CREATION   started <<<<<<<<<<
[2022-08-23 04:17:25,133: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-08-23 04:17:25,133: INFO: stage__02__base__model__creation]: layers are about to be defined
[2022-08-23 04:17:25,141: INFO: stage__02__base__model__creation]: layers are defined
[2022-08-23 04:17:25,283: INFO: stage__02__base__model__creation]: log model summary: 
 Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 conv2d (Conv2D)             (None, 178, 178, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 89, 89, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 87, 87, 32)        9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 43, 43, 32)       0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 59168)             0         
                                                                 
 dense (Dense)               (None, 128)               7573632   
                                                                 
 dense_1 (Dense)             (None, 2)                 258       
                                                                 
=================================================================
Total params: 7,584,034
Trainable params: 7,584,034
Non-trainable params: 0
_________________________________________________________________

[2022-08-23 04:17:25,291: INFO: common]: created directory at: data\model
[2022-08-23 04:17:25,360: INFO: stage__02__base__model__creation]: model is saved at data\model\init_model.h5
[2022-08-23 04:17:25,360: INFO: stage__02__base__model__creation]: >>>>>>>>> stage  INITIAL MODEL CREATION   completed <<<<<<<<<<<
[2022-08-23 04:17:25,800: INFO: main]: >>>>>>>>> stage  MAIN   completed <<<<<<<<<<<
